"use client";

import Link from "next/link";
import { useActionState, type ReactNode } from "react";
import { Check, Eye, ShieldAlert, X, XCircle } from "lucide-react";
import { updateModerationReportAction } from "@/app/admin/moderation/actions";

type Report = { id: string; targetType: string; targetId: string; reason: string; details: string; status: string; createdAt: string; reporterName: string };
function Action({ reportId, status, children, className = "" }: { reportId: string; status: string; children: ReactNode; className?: string }) { const [state, action, pending] = useActionState(updateModerationReportAction, {}); return <span className="admin-moderation-action"><form action={action}><input type="hidden" name="reportId" value={reportId} /><input type="hidden" name="status" value={status} /><button className={className} type="submit" disabled={pending}>{children}</button></form>{state.error ? <small><XCircle size={12} /> {state.error}</small> : null}</span>; }
function dateLabel(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "เมื่อสักครู่" : new Intl.DateTimeFormat("th-TH", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Bangkok" }).format(date); }
export default function AdminModerationPanel({ reports }: { reports: Report[] }) { return <main className="admin-moderation-page"><div className="admin-moderation-shell"><header className="admin-trophy-topbar"><Link href="/admin" className="admin-trophy-brand"><span>Arena</span><em>-Badminton</em></Link><nav><Link href="/admin">Admin Hub</Link><Link href="/profile">Profile</Link></nav><span className="admin-trophy-role"><ShieldAlert size={15} /> Moderation</span></header><section className="admin-moderation-hero"><div><p lang="en">Safety queue</p><h1>ศูนย์ตรวจสอบรายงาน</h1><span>ตรวจสอบ Report จาก Community, Marketplace, สนาม และ Guild พร้อมบันทึกผลการดำเนินการ</span></div><div aria-hidden="true">🛡️</div></section><section className="admin-moderation-list"><div className="admin-moderation-heading"><h2>รายการที่ยังไม่ปิด</h2><span>{reports.length} รายการ</span></div>{reports.length > 0 ? reports.map((report) => <article className="admin-moderation-row" key={report.id}><div className="admin-moderation-row__marker"><ShieldAlert size={19} /></div><div className="admin-moderation-row__body"><div><strong>{report.reason}</strong><span className={`admin-moderation-status admin-moderation-status--${report.status}`}>{report.status}</span></div><p>{report.details || "ไม่มีรายละเอียดเพิ่มเติม"}</p><small>{report.targetType} · {report.targetId.slice(0, 8)} · โดย {report.reporterName} · {dateLabel(report.createdAt)}</small></div><div className="admin-moderation-row__actions"><Action reportId={report.id} status="reviewing" className="admin-moderation-review"><Eye size={14} /> ตรวจสอบ</Action><Action reportId={report.id} status="resolved" className="admin-moderation-resolve"><Check size={14} /> ปิดเคส</Action><Action reportId={report.id} status="dismissed" className="admin-moderation-dismiss"><X size={14} /> ไม่รับเรื่อง</Action></div></article>) : <div className="admin-moderation-empty"><ShieldAlert size={30} /><strong>ไม่มี Report ที่รอดำเนินการ</strong><span>เมื่อมีผู้ใช้แจ้งปัญหา รายการจะเข้าคิวนี้</span></div>}</section><footer className="admin-moderation-footer"><Link href="/admin">กลับ Admin Hub</Link><span>การตรวจสอบสิทธิ์ทำซ้ำใน Supabase RPC</span></footer></div></main>; }
