"use client";

import { useActionState } from "react";
import { Check, CheckCircle2, ClipboardList, Gift, Plus, Sparkles, Target, XCircle } from "lucide-react";
import { claimGuildQuestAction, createGuildQuestAction, type GuildActionState } from "@/app/guilds/actions";

export type GuildQuestData = { id: string; title: string; description: string; questType: string; targetValue: number; rewardGuildExp: number; rewardExp: number; rewardItemName: string | null; status: string; startsAt: string; endsAt: string; progress: number; claimed: boolean };
type QuestItem = { id: string; name: string; icon: string };

const labels: Record<string, string> = { match_played: "แข่งให้ครบ", match_wins: "ช่วยกันคว้าชัย", members_joined: "ชวนสมาชิกใหม่", guild_exp: "สะสม Guild EXP" };
function dateLabel(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "ไม่ระบุเวลา" : new Intl.DateTimeFormat("th-TH", { dateStyle: "medium", timeZone: "Asia/Bangkok" }).format(date); }
function Feedback({ state }: { state: GuildActionState }) { if (!state.error && !state.message) return null; return <p className={state.error ? "guild-quest-feedback guild-quest-feedback--error" : "guild-quest-feedback"} role={state.error ? "alert" : "status"}>{state.error ? <XCircle size={14} /> : <Check size={14} />}{state.error ?? state.message}</p>; }

function QuestCard({ quest, guildId }: { quest: GuildQuestData; guildId: string }) {
  const [state, action, pending] = useActionState(claimGuildQuestAction, {});
  const percentage = Math.min(100, Math.round((quest.progress / Math.max(1, quest.targetValue)) * 100));
  return <article className="guild-quest-card"><div className="guild-quest-card__icon"><Target size={20} /></div><div className="guild-quest-card__body"><div className="guild-quest-card__top"><div><small>{labels[quest.questType] ?? quest.questType}</small><h3>{quest.title}</h3></div>{quest.claimed ? <span className="guild-quest-claimed"><CheckCircle2 size={13} /> รับแล้ว</span> : null}</div><p>{quest.description || "ภารกิจร่วมของสมาชิก Guild"}</p><div className="guild-quest-progress"><div><span>{quest.progress.toLocaleString("th-TH")} / {quest.targetValue.toLocaleString("th-TH")}</span><strong>{percentage}%</strong></div><div><span style={{ width: `${percentage}%` }} /></div></div><div className="guild-quest-card__reward"><span><Gift size={14} /> +{quest.rewardGuildExp.toLocaleString("th-TH")} Guild EXP</span>{quest.rewardExp > 0 ? <span>+{quest.rewardExp.toLocaleString("th-TH")} EXP</span> : null}{quest.rewardItemName ? <span>🎁 {quest.rewardItemName}</span> : null}<small>หมดเขต {dateLabel(quest.endsAt)}</small></div>{!quest.claimed && quest.progress >= quest.targetValue ? <form action={action}><input type="hidden" name="questId" value={quest.id} /><input type="hidden" name="guildId" value={guildId} /><button type="submit" className="guild-primary-action" disabled={pending}>{pending ? "กำลังรับ..." : "รับรางวัลภารกิจ"}<Gift size={14} /></button></form> : null}<Feedback state={state} /></div></article>;
}

function QuestCreateForm({ guildId, items }: { guildId: string; items: QuestItem[] }) {
  const [state, action, pending] = useActionState(createGuildQuestAction, {});
  return <details className="guild-quest-create"><summary><Plus size={16} /> สร้างภารกิจใหม่</summary><form action={action}><input type="hidden" name="guildId" value={guildId} /><div className="guild-quest-form-grid"><label><span>ชื่อภารกิจ</span><input name="title" maxLength={160} required placeholder="เช่น ลงสนามให้ครบ 10 แมตช์" /></label><label><span>ประเภท</span><select name="questType" defaultValue="match_played"><option value="match_played">แข่งให้ครบ</option><option value="match_wins">ช่วยกันชนะ</option><option value="members_joined">สมาชิกเข้าร่วม</option><option value="guild_exp">สะสม Guild EXP</option></select></label><label><span>เป้าหมาย</span><input name="targetValue" type="number" min="1" max="1000000" defaultValue="10" required /></label><label><span>รางวัล Guild EXP</span><input name="rewardGuildExp" type="number" min="0" max="100000000" defaultValue="100" required /></label><label><span>รางวัล EXP ผู้เล่น</span><input name="rewardExp" type="number" min="0" max="100000000" defaultValue="0" required /></label><label><span>Item รางวัล</span><select name="rewardItemId" defaultValue=""><option value="">ไม่แจก Item</option>{items.map((item) => <option key={item.id} value={item.id}>{item.icon} {item.name}</option>)}</select></label><label className="guild-quest-form-grid__wide"><span>รายละเอียด</span><textarea name="description" maxLength={1000} placeholder="บอกสมาชิกว่าเควสนี้ทำอย่างไร" /></label><label><span>เริ่ม</span><input name="startsAt" type="datetime-local" /></label><label><span>หมดเขต</span><input name="endsAt" type="datetime-local" /></label></div><button type="submit" className="guild-primary-action" disabled={pending}><ClipboardList size={15} /> {pending ? "กำลังสร้าง..." : "สร้างภารกิจ"}</button><Feedback state={state} /></form></details>;
}

export default function GuildQuestPanel({ guildId, quests, items, isManager }: { guildId: string; quests: GuildQuestData[]; items: QuestItem[]; isManager: boolean }) {
  return <section className="guild-detail-panel guild-quest-panel"><div className="guild-detail-panel__heading"><div><p lang="en">Guild Missions</p><h2><Sparkles size={19} /> ภารกิจ Guild</h2></div><span>{quests.length} ภารกิจ</span></div>{quests.length > 0 ? <div className="guild-quest-list">{quests.map((quest) => <QuestCard key={quest.id} quest={quest} guildId={guildId} />)}</div> : <div className="guild-detail-empty"><ClipboardList size={25} /><span>ยังไม่มีภารกิจ ให้ผู้ดูแลสร้าง Quest แรกของ Guild</span></div>}{isManager ? <QuestCreateForm guildId={guildId} items={items} /> : null}</section>;
}
