"use client";

import Link from "next/link";
import { useActionState } from "react";
import { AlertTriangle, Check, ShieldCheck, XCircle } from "lucide-react";
import { createModerationReportAction } from "@/app/moderation/actions";

export default function ModerationReportForm({ targetType, targetId, returnTo }: { targetType: string; targetId: string; returnTo: string }) {
  const [state, action, pending] = useActionState(createModerationReportAction, {});
  return <main className="moderation-report-page"><div className="moderation-report-shell"><header className="groups-topbar"><Link href={returnTo} className="groups-back">กลับหน้าก่อนหน้า</Link><Link href="/" className="groups-brand"><span>Arena</span><em>-Badminton</em></Link><span className="organizer-user-chip"><ShieldCheck size={15} /> Safety</span></header><section className="moderation-report-card"><div className="moderation-report-card__icon"><AlertTriangle size={25} /></div><p lang="en">Community safety</p><h1>รายงานเนื้อหา</h1><span>ทีมงานจะตรวจสอบรายงานนี้ตามกติกา Community และเก็บข้อมูลไว้เพื่อการดูแลระบบ</span><form action={action}><input type="hidden" name="targetType" value={targetType} /><input type="hidden" name="targetId" value={targetId} /><input type="hidden" name="returnTo" value={returnTo} /><label><span>เหตุผลที่รายงาน *</span><select name="reason" defaultValue="เนื้อหาไม่เหมาะสม" required><option>เนื้อหาไม่เหมาะสม</option><option>สแปมหรือโฆษณา</option><option>หลอกลวงหรือขอข้อมูลสำคัญ</option><option>คุกคามหรือใช้ถ้อยคำรุนแรง</option><option>ละเมิดลิขสิทธิ์</option></select></label><label><span>รายละเอียดเพิ่มเติม</span><textarea name="details" maxLength={1000} placeholder="เล่าเหตุการณ์หรือจุดที่อยากให้ทีมงานตรวจสอบ" /></label><div className="moderation-report-actions"><Link href={returnTo} className="group-secondary-action">ยกเลิก</Link><button type="submit" className="group-primary-action" disabled={pending}>{pending ? "กำลังส่ง..." : "ส่งรายงาน"}</button></div>{state.error ? <p className="moderation-report-feedback moderation-report-feedback--error" role="alert"><XCircle size={15} /> {state.error}</p> : state.message ? <p className="moderation-report-feedback" role="status"><Check size={15} /> {state.message}</p> : null}</form></section><footer className="moderation-report-footer">Report ID จะถูกสร้างโดยระบบ · โปรดใช้ฟังก์ชันนี้เมื่อพบสิ่งที่ต้องการให้ทีมงานช่วยตรวจสอบ</footer></div></main>;
}
